const express = require('express');
const HopDongController = require('../controllers/HopDongController');
const auth = require('../middlewares/auth');
const ipFilterMiddleware = require('../middlewares/ipWhitelist');
const router = express.Router();
const { createLoaiHopDong } = require('../controllers/LoaiHopDongController');
router.post('/renderHDPreview', auth.verifyTokenPartner, HopDongController.renderHD);
router.get('/chiTietHopHong/:templateId', auth.verifyTokenPartner, HopDongController.getChiTietHD);
router.post('/loaiHopDong', createLoaiHopDong);
module.exports = router;